# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

TestCases = {
    "REL_BASE_01": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [64],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [8],
    },
    "REL_BASE_02": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [64],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["bf16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [8],
    },
    "REL_BASE_03": {
        "B": [2],
        "N1": [8],
        "N2": [2],
        "S1": [256],
        "S2": [576],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [24],
        "W": [24],
    },
    "REL_BASE_04": {
        "B": [1],
        "N1": [8],
        "N2": [1],
        "S1": [512],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["bf16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [32],
        "W": [32],
    },
    "REL_BASE_05": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [True],
        "H": [16],
        "W": [16],
    },
    "REL_BASE_06": {
        "B": [1],
        "N1": [4],
        "N2": [2],
        "S1": [256],
        "S2": [512],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BSND"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [32],
    },
    "REL_BASE_07": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "scale": [0.03],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [16],
    },
    "REL_HW_SQUARE_01": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [16],
    },
    "REL_HW_TALL_02": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [4],
    },
    "REL_HW_WIDE_03": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [4],
        "W": [64],
    },
    "REL_HW_MIN_04": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [16],
        "S2": [1],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [1],
        "W": [1],
    },
    "REL_HW_PRIME_05": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [221],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [13],
        "W": [17],
    },
    "REL_HW_S640_A": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [256],
        "S2": [640],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [20],
        "W": [32],
    },
    "REL_HW_S640_B": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [256],
        "S2": [640],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [32],
        "W": [20],
    },
    "REL_HW_S640_C": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [256],
        "S2": [640],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [10],
        "W": [64],
    },
    "REL_HW_S640_D": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [256],
        "S2": [640],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [10],
    },
    "REL_S2_EXACT_01": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [128],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [16],
    },
    "REL_S2_TAIL_02": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [200],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [25],
    },
    "REL_S2_SWEEP_640": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [640],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [40],
        "W": [16],
    },
    "REL_S2_SWEEP_768": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [768],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [48],
        "W": [16],
    },
    "REL_S2_SWEEP_1024": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [16],
    },
    "REL_S2_SWEEP_2048": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [2048],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [32],
    },
    "REL_S2_SWEEP_4096": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [4096],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [64],
    },
    "REL_S1_ONE_01": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [1],
        "S2": [64],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [8],
    },
    "REL_S1_UNALIGN_02": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [33],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [16],
    },
    "BNSD": {
        "B": [4],
        "N1": [9],
        "N2": [1],
        "S1": [1111],
        "S2": [4096],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "seqused_q": [[512, 512, 512, 512]],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [64],
    },
    "REL_S1_LARGE_04": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [4096],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [64],
        "W": [16],
    },
    "REL_SEQ_MIX_01": {
        "B": [4],
        "N1": [4],
        "N2": [1],
        "S1": [1024],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "seqused_q": [[512, 1024, 300, 1]],
        "return_softmax_lse": [False],
        "H": [32],
        "W": [32],
    },
    "REL_SEQ_ONE_02": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "seqused_q": [[1]],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [16],
    },
    "REL_SEQ_FULL_03": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [256],
        "S2": [256],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "seqused_q": [[256]],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [16],
    },
    "REL_ZERO_01": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [64],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [8],
        "W": [8],
        "rel_mode": ["zero"],
    },
    "REL_RANGE_02": {
        "B": [1],
        "N1": [2],
        "N2": [2],
        "S1": [128],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [32],
        "W": [32],
        "rel_range": [(-10, 10)],
    },
    "REL_CROSS_01": {
        "B": [2],
        "N1": [16],
        "N2": [4],
        "S1": [2048],
        "S2": [1024],
        "D": [64],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BSND"],
        "Dtype": ["bf16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "seqused_q": [[1024, 2048]],
        "return_softmax_lse": [True],
        "H": [32],
        "W": [32],
    },
    "BSND_03": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [128],
        "D": [64],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "layout_out": ["BSND"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "return_softmax_lse": [False],
        "H": [16],
        "W": [8],
    },
    "TND_05": {
        "B": [1],
        "N1": [1],
        "N2": [1],
        "S1": [128],
        "S2": [256],
        "D": [64],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "layout_out": ["TND"],
        "Dtype": ["fp16"],
        "q_range": [(-5, 5)],
        "k_range": [(-5, 5)],
        "v_range": [(-5, 5)],
        "mask_mode": [0],
        "cu_seqlens_q": [[0, 128, 256]],
        "cu_seqlens_kv": [[0, 1024, 2048]],
        "return_softmax_lse": [False],
        "H": [32],
        "W": [32],
    },
}
