#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

import torch

# 当前由于torchair拦截的原因，kv_type为float8_e4m3fn时只能传None
TEST_PARAMS = {
    "TND_PA": {
        "Testcase_Prefix": ["runpy_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["hifloat8"],
        "B": [22],
        "T1": [22],
        "S1": [1],
        "S2": [128],
        "N1": [48],
        "N2": [1],
        "D": [512],
        "K": [2048],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [2],
        "value_quant_mode": [2],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "actual_seq_q": [
            [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
            ]
        ],
        "actual_seq_kv": [
            [
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                128,
            ]
        ],
    },
    "BSND_BSND": {
        "Testcase_Prefix": ["runpy_style"],
        "layout_query": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": [None],
        "B": [1],
        "S1": [1],
        "S2": [4096],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [2048],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [2],
        "value_quant_mode": [2],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [256],
        "actual_seq_q": [[1]],
        "actual_seq_kv": [[4096]],
    },
    "BSND_PA": {
        "Testcase_Prefix": ["runpy_style"],
        "layout_query": ["BSND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": [None],
        "B": [18],
        "T1": [54],
        "S1": [3],
        "S2": [3072],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [2048],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [2],
        "value_quant_mode": [2],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [16],
        "actual_seq_q": [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],
        "actual_seq_kv": [
            [
                2208,
                2112,
                800,
                2112,
                2720,
                2080,
                1248,
                2816,
                2272,
                2976,
                3008,
                2784,
                2272,
                1696,
                2496,
                2144,
                2432,
                3072,
            ]
        ],
    },
    "TND_TND": {
        "Testcase_Prefix": ["runpy_style"],
        "layout_query": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "kv_type": [None],
        "B": [22],
        "T1": [22],
        "T2": [128],
        "S1": [1],
        "S2": [128],
        "N1": [48],
        "N2": [1],
        "D": [512],
        "K": [2048],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [2],
        "value_quant_mode": [2],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "actual_seq_q": [
            [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
            ]
        ],
        "actual_seq_kv": [
            [
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                128,
            ]
        ],
    },
    "TQ4_TND_PA_BF16": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_FP16": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.float16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_BSND_PA_BF16": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["BSND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_BF16_LONG": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [8],
        "S1": [8],
        "S2": [256],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [256],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [2],
        "actual_seq_q": [[8]],
        "actual_seq_kv": [[256]],
    },
    "TQ4_TND_PA_BF16_VARY_KV": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [4],
        "T1": [4],
        "S1": [1],
        "S2": [256],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [256],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [6],
        "actual_seq_q": [[1, 2, 3, 4]],
        "actual_seq_kv": [[64, 128, 192, 256]],
    },
    "TQ4_TND_PA_BF16_TOPK": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [256],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [64],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [2],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[256]],
    },
    "TQ4_TND_PA_BF16_HEADS": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [2],
        "S1": [2],
        "S2": [128],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[2]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_BF16_NONCAUSAL": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [0],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_BF16_SCALE": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [128],
        "scale_value": [0.125],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [1],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_FP16_LONG": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.float16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [8],
        "S1": [8],
        "S2": [256],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [256],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [2],
        "actual_seq_q": [[8]],
        "actual_seq_kv": [[256]],
    },
    "TQ4_BSND_PA_BF16_LONG": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["BSND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "S1": [8],
        "S2": [256],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [256],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [2],
        "actual_seq_q": [[8]],
        "actual_seq_kv": [[256]],
    },
    "TQ4_TND_PA_BF16_CHUNK": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [7],
        "S1": [7],
        "S2": [384],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [384],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [3],
        "actual_seq_q": [[7]],
        "actual_seq_kv": [[384]],
    },
    "TQ4_TND_PA_BF16_CODEBOOK": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [1],
        "S1": [1],
        "S2": [512],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [512],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [128],
        "block_num": [4],
        "actual_seq_q": [[1]],
        "actual_seq_kv": [[512]],
    },
    # Block-wise sparse and short/tail cases exercise packed-slot addressing.
    "TQ4_TND_PA_BF16_BLOCK4": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [64],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [4],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [16],
        "block_num": [8],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_FP16_BLOCK4": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.float16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [4],
        "S1": [4],
        "S2": [128],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [64],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [4],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [0],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [16],
        "block_num": [8],
        "actual_seq_q": [[4]],
        "actual_seq_kv": [[128]],
    },
    "TQ4_TND_PA_BF16_SHORT": {
        "Testcase_Prefix": ["tq4_style"],
        "layout_query": ["TND"],
        "layout_kv": ["PA_BSND"],
        "q_type": [torch.bfloat16],
        "kv_type": ["int8"],
        "B": [1],
        "T1": [1],
        "S1": [1],
        "S2": [64],
        "N1": [8],
        "N2": [1],
        "D": [512],
        "K": [64],
        "scale_value": [0.041666666666666664],
        "key_quant_mode": [3],
        "value_quant_mode": [3],
        "sparse_block_size": [1],
        "tile_size": [128],
        "rope_head_dim": [64],
        "sparse_mode": [3],
        "attention_mode": [2],
        "quant_scale_repo_mode": [1],
        "block_size": [16],
        "block_num": [4],
        "actual_seq_q": [[1]],
        "actual_seq_kv": [[64]],
    },
}

ENABLED_PARAMS = [TEST_PARAMS[key] for key in TEST_PARAMS.keys()]
